//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeDrugChecker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeDrugChecker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนยาแพ้:.
        /// </summary>
        public static string allergy_encounter_status {
            get {
                return ResourceManager.GetString("allergy_encounter_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ป่วยแพ้ยา.
        /// </summary>
        public static string allergy_status_hasEntries {
            get {
                return ResourceManager.GetString("allergy_status_hasEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มียาที่แพ้.
        /// </summary>
        public static string allergy_status_normal {
            get {
                return ResourceManager.GetString("allergy_status_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการแพ้ยา.
        /// </summary>
        public static string allergy_title {
            get {
                return ResourceManager.GetString("allergy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยาที่แพ้.
        /// </summary>
        public static string allergyDG_agent {
            get {
                return ResourceManager.GetString("allergyDG_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN.
        /// </summary>
        public static string allergyDG_hn {
            get {
                return ResourceManager.GetString("allergyDG_hn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อาการ.
        /// </summary>
        public static string allergyDG_symptom {
            get {
                return ResourceManager.GetString("allergyDG_symptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาดในการตั้งค่า.
        /// </summary>
        public static string db_setting_applyFailed {
            get {
                return ResourceManager.GetString("db_setting_applyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ IP.
        /// </summary>
        public static string dbsetting_address {
            get {
                return ResourceManager.GetString("dbsetting.address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งาน.
        /// </summary>
        public static string dbsetting_applybtn {
            get {
                return ResourceManager.GetString("dbsetting.applybtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตั้งค่าสำเร็จ.
        /// </summary>
        public static string dbsetting_applyPass {
            get {
                return ResourceManager.GetString("dbsetting_applyPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผ่าน.
        /// </summary>
        public static string dbsetting_password {
            get {
                return ResourceManager.GetString("dbsetting.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทดสอบการเชื่อมต่อ.
        /// </summary>
        public static string dbsetting_testbtn {
            get {
                return ResourceManager.GetString("dbsetting.testbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถเชื่อมต่อฐานข้อมูลได้.
        /// </summary>
        public static string dbsetting_testfail {
            get {
                return ResourceManager.GetString("dbsetting_testfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทดสอบเชื่อมต่อฐานข้อมูลสำเร็จ.
        /// </summary>
        public static string dbsetting_testpass {
            get {
                return ResourceManager.GetString("dbsetting_testpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีฐานข้อมูล.
        /// </summary>
        public static string dbsetting_username {
            get {
                return ResourceManager.GetString("dbsetting.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิด Note.
        /// </summary>
        public static string di_closeNoteBtnTxt {
            get {
                return ResourceManager.GetString("di_closeNoteBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คลิกเพื่อเปิด/ปิด Note.
        /// </summary>
        public static string di_defaultNoteBtntxt {
            get {
                return ResourceManager.GetString("di_defaultNoteBtntxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน Drug Interaction ที่พบ:.
        /// </summary>
        public static string di_encounter_status {
            get {
                return ResourceManager.GetString("di_encounter_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยาลำดับแรก.
        /// </summary>
        public static string di_firstdrug {
            get {
                return ResourceManager.GetString("di_firstdrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โน้ต.
        /// </summary>
        public static string di_note {
            get {
                return ResourceManager.GetString("di_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เปิด Note.
        /// </summary>
        public static string di_openNoteBtnTxt {
            get {
                return ResourceManager.GetString("di_openNoteBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยาลำดับที่สอง.
        /// </summary>
        public static string di_seconddrug {
            get {
                return ResourceManager.GetString("di_seconddrug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ป่วยมี Drug Interaction(s).
        /// </summary>
        public static string di_status_hasEntries {
            get {
                return ResourceManager.GetString("di_status_hasEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มี Drug Interaction(s).
        /// </summary>
        public static string di_status_normal {
            get {
                return ResourceManager.GetString("di_status_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูล Drug Interactions.
        /// </summary>
        public static string di_title {
            get {
                return ResourceManager.GetString("di_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปภาพยา.
        /// </summary>
        public static string lbl_drugImgGB {
            get {
                return ResourceManager.GetString("lbl_drugImgGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการยา.
        /// </summary>
        public static string lbl_drugLstGB {
            get {
                return ResourceManager.GetString("lbl_drugLstGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อยา.
        /// </summary>
        public static string lbl_drugNameGCol {
            get {
                return ResourceManager.GetString("lbl_drugNameGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน่วย.
        /// </summary>
        public static string lbl_drugUnitGCol {
            get {
                return ResourceManager.GetString("lbl_drugUnitGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผู้ป่วย.
        /// </summary>
        public static string lbl_hn {
            get {
                return ResourceManager.GetString("lbl_hn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสยา.
        /// </summary>
        public static string lbl_icode {
            get {
                return ResourceManager.GetString("lbl_icode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสยา.
        /// </summary>
        public static string lbl_icodeGCol {
            get {
                return ResourceManager.GetString("lbl_icodeGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ป่วย.
        /// </summary>
        public static string lbl_patientInfoGB {
            get {
                return ResourceManager.GetString("lbl_patientInfoGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string lbl_patientName {
            get {
                return ResourceManager.GetString("lbl_patientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนยา.
        /// </summary>
        public static string lbl_qtyGCol {
            get {
                return ResourceManager.GetString("lbl_qtyGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาจ่ายยา.
        /// </summary>
        public static string lbl_rxtimeGCol {
            get {
                return ResourceManager.GetString("lbl_rxtimeGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหาผู้ป่วยด้วย HN.
        /// </summary>
        public static string lbl_searchPatientGB {
            get {
                return ResourceManager.GetString("lbl_searchPatientGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำแนะนำการใช้ยา.
        /// </summary>
        public static string lbl_shortlstGCol {
            get {
                return ResourceManager.GetString("lbl_shortlstGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เวลาเข้ารับบริการ.
        /// </summary>
        public static string lbl_vstdateGCol {
            get {
                return ResourceManager.GetString("lbl_vstdateGCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด.
        /// </summary>
        public static string msg_DImgError {
            get {
                return ResourceManager.GetString("msg_DImgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผู้ป่วยไม่ถูกต้อง.
        /// </summary>
        public static string msg_hnNotConform {
            get {
                return ResourceManager.GetString("msg_hnNotConform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สแกนหรือใส่รหัสยาก่อน.
        /// </summary>
        public static string msg_icodeEmpty {
            get {
                return ResourceManager.GetString("msg_icodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด.
        /// </summary>
        public static string msg_icodeError {
            get {
                return ResourceManager.GetString("msg_icodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถูกเช็คแล้ว.
        /// </summary>
        public static string msg_icodeFound {
            get {
                return ResourceManager.GetString("msg_icodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการยาโหลดไม่ได้ หรือไม่มีข้อมูล.
        /// </summary>
        public static string msg_icodeListEmpty {
            get {
                return ResourceManager.GetString("msg_icodeListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบยานี้ในรายการยา.
        /// </summary>
        public static string msg_icodeNotFound {
            get {
                return ResourceManager.GetString("msg_icodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เกิดข้อผิดพลาด.
        /// </summary>
        public static string msg_patientError {
            get {
                return ResourceManager.GetString("msg_patientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบผู้ป่วยหมายเลข.
        /// </summary>
        public static string msg_patientFound {
            get {
                return ResourceManager.GetString("msg_patientFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบผู้ป่วยหมายเลข.
        /// </summary>
        public static string msg_patientNotFound {
            get {
                return ResourceManager.GetString("msg_patientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทข้อมูลในฐานข้อมูล.
        /// </summary>
        public static string setting_datastage {
            get {
                return ResourceManager.GetString("setting_datastage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบฐานข้อมูล.
        /// </summary>
        public static string setting_dbtitle {
            get {
                return ResourceManager.GetString("setting_dbtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การตั้งค่า.
        /// </summary>
        public static string setting_title {
            get {
                return ResourceManager.GetString("setting_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เคลียร์.
        /// </summary>
        public static string txt_clearBtn {
            get {
                return ResourceManager.GetString("txt_clearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string txt_hnSearchBtn {
            get {
                return ResourceManager.GetString("txt_hnSearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เช็ครหัสยา.
        /// </summary>
        public static string txt_icodeSendBtn {
            get {
                return ResourceManager.GetString("txt_icodeSendBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังโหลดข้อมูล....
        /// </summary>
        public static string txt_loading {
            get {
                return ResourceManager.GetString("txt_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- ไม่มีข้อมูลแสดง ---.
        /// </summary>
        public static string txt_noDataDG {
            get {
                return ResourceManager.GetString("txt_noDataDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ไม่มีรูปภาพแสดง ---.
        /// </summary>
        public static string txt_noDImg {
            get {
                return ResourceManager.GetString("txt_noDImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนยาที่เหลือในรายการ: .
        /// </summary>
        public static string txt_remDrug {
            get {
                return ResourceManager.GetString("txt_remDrug", resourceCulture);
            }
        }
    }
}
